# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  check:
    desc: Run eslint, prettier and vitest
    cmds:
      - npm run lint
      - npm run format
      - npm run test:unit-run