// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAddon(arg1) {
  return window['go']['main']['App']['DeleteAddon'](arg1);
}

export function GetAddons() {
  return window['go']['main']['App']['GetAddons']();
}

export function GetLocalAddons(arg1) {
  return window['go']['main']['App']['GetLocalAddons'](arg1);
}

export function GetRemoteAddons(arg1) {
  return window['go']['main']['App']['GetRemoteAddons'](arg1);
}

export function InstallAddon(arg1, arg2) {
  return window['go']['main']['App']['InstallAddon'](arg1, arg2);
}

export function UpdateAddon(arg1) {
  return window['go']['main']['App']['UpdateAddon'](arg1);
}
