// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteAddon(arg1:number):Promise<void>;

export function GetAddons(arg1:boolean):Promise<main.AddonMap>;

export function GetLocalAddons(arg1:boolean):Promise<main.AddonMap>;

export function GetRemoteAddons(arg1:boolean):Promise<main.AddonMap>;

export function InstallAddon(arg1:number,arg2:boolean):Promise<void>;

export function UpdateAddon(arg1:number):Promise<void>;
