// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAddons():Promise<main.ParentAddonMap>;

export function GetLocalAddons():Promise<main.ParentAddonMap>;

export function GetRemoteAddons():Promise<main.ParentAddonMap>;
