// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { database } from '../models'
import { remote } from '../models'

export function GetLocalAddons(): Promise<Array<database.Addon>>

export function GetRemoteAddons(): Promise<Array<remote.RemoteAddon>>
