name: Testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.26'

      - name: Install ubuntu dependencies
        run: sudo apt install -y nodejs

      - name: Build frontend
        run: |
          npm install --global corepack@latest
          corepack enable pnpm
          pnpm --prefix frontend install
          pnpm --prefix frontend run build

      - name: Golang tests
        run: go test -v ./...

      - name: JS tests
        run: pnpm run test:unit-run
