// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchRemotePlugins() {
  return window['go']['main']['App']['FetchRemotePlugins']();
}

export function GetInstalledPlugins() {
  return window['go']['main']['App']['GetInstalledPlugins']();
}

export function InstallPlugin(arg1) {
  return window['go']['main']['App']['InstallPlugin'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function UpdatePlugins(arg1) {
  return window['go']['main']['App']['UpdatePlugins'](arg1);
}
