// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePlugin(arg1, arg2) {
  return window['go']['main']['App']['DeletePlugin'](arg1, arg2);
}

export function GetInstalledPlugins() {
  return window['go']['main']['App']['GetInstalledPlugins']();
}

export function GetRemotePlugins() {
	return window['go']['main']['App']['GetRemotePlugins']();
}

export function GetSettings() {
	return window['go']['main']['App']['GetSettings']();
}

export function InstallPlugin(arg1) {
  return window['go']['main']['App']['InstallPlugin'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchLocal(arg1) {
	return window['go']['main']['App']['SearchLocal'](arg1);
}

export function SearchRemote(arg1) {
	return window['go']['main']['App']['SearchRemote'](arg1);
}

export function UpdatePlugins(arg1) {
  return window['go']['main']['App']['UpdatePlugins'](arg1);
}
