// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchRemotePlugins() {
  return window['go']['main']['App']['FetchRemotePlugins']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallPlugin(arg1) {
  return window['go']['main']['App']['InstallPlugin'](arg1);
}
