// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function DeletePlugin(arg1:string,arg2:string):Promise<Array<entities.LocalPluginEntity>>;

export function FetchRemotePlugins():Promise<Array<entities.RemotePluginEntity>>;

export function GetInstalledPlugins():Promise<Array<entities.LocalPluginEntity>>;

export function InstallPlugin(arg1:string):Promise<Array<entities.LocalPluginEntity>>;

export function SaveSettings(arg1:string):Promise<void>;

export function UpdatePlugins(arg1:any):Promise<void>;
