// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';
import {settings} from '../models';

export function DeletePlugin(arg1:string,arg2:string):Promise<Array<entities.LocalPluginEntity>>;

export function GetInstalledPlugins():Promise<Array<entities.LocalPluginEntity>>;

export function GetRemotePlugins():Promise<Array<entities.RemotePluginEntity>>;

export function GetSettings():Promise<settings.Settings>;

export function InstallPlugin(arg1:string):Promise<Array<entities.RemotePluginEntity>>;

export function SaveSettings(arg1:{[key: string]: string}):Promise<void>;

export function SearchLocal(arg1:string):Promise<Array<entities.LocalPluginEntity>>;

export function SearchRemote(arg1:string):Promise<Array<entities.RemotePluginEntity>>;

export function UpdatePlugins(arg1:any):Promise<void>;
